<a href="https://colab.research.google.com/github/kgurucharan2003/machine_learning_projects/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

Data Preprocessing

In [3]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
Y = dataset.iloc[:,-1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(Y)

[1 0 1 ... 1 1 0]


Encoding Categorical Data

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])


In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('endoer',OneHotEncoder(),[1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the data into trianing and testing sets

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state=0)


Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units = 6,activation ='relu'))

Adding Second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the output layer

In [22]:
ann.add(tf.keras.layers.Dense(units =1,activation='sigmoid'))

Compiling the ANN

In [23]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics = ['accuracy'])

Training the ANN on the Training Set

In [25]:
ann.fit(X_train,Y_train,batch_size =32,epochs =100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7588
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4598 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4415 - accuracy: 0.7966
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4326 - accuracy: 0.7997
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4265 - accuracy: 0.8009
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4214 - accuracy: 0.8015
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4166 - accuracy: 0.8067
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4114 - accuracy: 0.8105
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.8226
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3961 - accura

Making predictions and Evaluating the Model

In [27]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])>0.5))

1/1 [==============================] - 0s 230ms/step
[[0.12649208]]


Predicting Test Results

In [29]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 0s 4ms/step
[[1 0]
 [1 1]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 0]]


Confusion Matrix

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[   0 1595]
 [   0  405]]


0.2025